### ISSUE TITLE
Adding JQuery to main.js

### ISSUE THREAD

**Issue by TLMcode** [n33/baseline#13]
I recently upgraded from skel 1.0.x baseline and noticed jQuery wasn't working in main.js skel.on( "init" ){} etc.
I changed the function to:
`(function($) {
// main js stuff})
(jQuery);`
jQuery works in main.js now but I was wondering if this poses any issues to the vanilla that's there already?
Thanks for any guidance.

**Comment by ajlkn** [comment]
Nope, should work fine, but I suggest rewriting it to take advantage of jQuery since it does a lot of stuff more elegantly (eg. the events and class stuff).

(PS: sorry for the delay; busy af :)
