### ISSUE TITLE
why no noscripts or shivs in v3.x ?

### ISSUE THREAD

**Issue by TLMcode** [n33/baseline#14]
Are noscripts and shivs handled internally somehow? I notice there are no reference to files.
wondering, ty

**Comment by ajlkn** [comment]
Ah yeah, they're excluded by default now. A lot of folks don't bother with IE8/9 support these days, and `<noscript>` isn't needed anymore since you're not losing anything critical when JS is turned off.

(PS: sorry for the delay; busy af :)
