### ISSUE TITLE
Support for not-$breakpoint and only-$breakpoint classes

### ISSUE THREAD

**Issue by ryanmadden** [n33/baseline#2]
Hi AJ,

I'm currently working with skel-baseline v3.0.0-dev and I was looking for how to use the not-$breakpoint and only-$breakpoint classes that were (to my knowledge) avaliable in older versions through skel layout. Are these classes supported in the current version of baseline?

The docs are a little unclear right now, it looks like you're folding skel layout into the core sass for baseline..? Anyway, I dove into the sass and wrote in support for those classes. I can submit a PR if you'd like but I was mainly interested in seeing if those are already implemented in a different way.

Thanks for building cool stuff!

-Ryan

**Comment by ajlkn** [comment]
Per our conversation over the twitters, this will be coming in a future update once I work out the weirdness `only-*` and `not-*` has w/multiple active breakpoints.
