### ISSUE TITLE
input type=submit disabled in form post

### ISSUE THREAD

**Issue by nicholasinclan** [n33/baseline#7]
sorry for posting in the wrong place, I had thought I was under baseline.

added a simple form post to a layout, and it appears the below line is causing the submit button from submitting any form.

var addEventsListener=function(o,t,e){var n,i=t.split(" ");for(n in i)o.addEventListener(i[n],e)} 

No errors, or warnings in console, simply won't submit. I've commented that specific line out and the form submits with no problems, however, obviously the rest of the site breaks with the above line is commented out.

**Comment by n33** [comment]
Hmm, try changing:

`o.addEventListener(`

to:

`addEventListener(o,`

**Comment by ajlkn** [comment]
Do you have this live anywhere I can look at?

**Comment by nicholasinclan** [comment]
yeah, see below.

http://teamgoalsongainz.com/

let me know when your done, so I can put the site back in maintenance mode, the form is in the footer

**Comment by ajlkn** [comment]
Hmm, form's not submitting, but I'm not seeing any console errors either. Maybe it's your `onsubmit` attribute doing something weird?

**Comment by nicholasinclan** [comment]
I'll look more into that but, when I comment out the below code the form works. Is there something the below code has in it that effects the listening event on a form?

var addEventsListener=function(o,t,e){var n,i=t.split(" ");for(n in i)o.addEventListener(i[n],e)}

**Comment by ajlkn** [comment]
Nope. All that function does is bind an event listener to multiple events on an element.

**Comment by nicholasinclan** [comment]
n33,
thanks for the feedback, did some more research tonight and located a more specific part of the code that is affecting the form submission

```
$body.addEventListener('click', function(event){

    //event.preventDefault();  <- ***specific line that is causing the form submit button not to work

    event.stopPropagation();

    $body.classList.remove('navPanel-visible');                     

});
```

do you have any details around this specific line? or documentation on what exactly its doing? if I uncomment it, it causes the form submit not to fire. if I comment it out the form submit works...

**Comment by ajlkn** [comment]
Doesn't appear to be part of Baseline, but that particular bit of code you're looking at probably closes the off-canvas navigation when you click anywhere in the body.

That said, you can remove the `preventDefault()` and `stopPropagation()` calls and all should be well.
